
[site]
url = "https://huper.haodf.net"
name = "HUPER 杂志"
description = "专注于SRE平台化建设，探讨SRE生态体系是如何在公司落地推进的。"

locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "问答", url = "/faq" },
  { name = "GitHub", url = "https://github.com/zineland/huper" },
]

[authors]
weetime = { avatar = "/static/avatar/weetime.jpeg", editor = true, bio = """
<p class="text-center">
《HUPER 杂志》责任编辑，目前就职于好大夫在线
</p>

> 申明：个人文章仅代表个人观点，与雇主无关。

可以通过如下方式联系到我：
- [GitHub](https://github.com/weetime)
""" }
tianzhou = { avatar = "/static/avatar/tianzhou.jpg", bio = """
<p class="text-center">
bytebase.com 首席涂鸦官
</p>

> 申明：个人文章代表不了公司观点。

可以通过如下方式联系到我：
- [GitHub](https://github.com/tianzhou)
- [Twitter](https://twitter.com/tianzhouchen)
""" }


[theme]
primary_color = "#ffb52f"
main_color = "#000"
link_color = "#e07312"
background_image = "/static/pattern.svg"
head_template = "templates/head.html"
footer_template = "templates/footer.html"
article_extend_template = "templates/article-extend.html"

[markdown]
highlight_theme = "ayu-light"

[[issue]]
slug = "s1"
number = 1
title = "第一季"
path = "content/issue-1"
intro = "content/issue-1/intro.md"
