[[article]]
slug = "retool"
file = "1-retool.md"
title = "Retool: Raising less money at lower valuations"
author = "Weetime"
cover = "/static/s1/1/retool.png"
pub_date = "2021-12-23"
publish = true
featured = true

[[article]]
slug = "wind-rises"
file = "1-wind-rises.md"
title = "起风了"
author = "Weetime"
cover = "/static/s1/1/retool.png"
pub_date = "2022-07-23"
publish = true
featured = true

[[article]]
slug = "hup"
file = "1-hup.md"
title = "探索To-D,落地好大夫效能平台"
author = "Weetime"
cover = "/static/s1/1/retool.png"
pub_date = "2023-06-12"
publish = true
featured = true